backend:
  name: git-gateway
  branch: main

local_backend: true

logo_url: https://toneeldevalk.netlify.app/favicon.svg

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "voorstellingen"
    label: "Voorstellingen"
    folder: "src/content/voorstellingen"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Auteur"
        name: "author"
        widget: "string"
        required: false
      - label: "Regie"
        name: "director"
        widget: "string"
        required: false
      - label: "Locatie"
        name: "location"
        widget: "string"
        default: "Magdalenazaal, Brugge"
      - label: "Korte Samenvatting"
        name: "summary"
        widget: "text"
      - label: "Datum tekst (bijv. Nov 2025)"
        name: "date"
        widget: "string"
      - label: "Speeldata & Tijden"
        name: "schedule"
        widget: "list"
        summary: "{{fields.time}}"
        fields:
          - label: "Dag/Tijdstip"
            name: "time"
            widget: "string"
            hint: "Bijv: 21 November 2025 - 20:00"
      - label: "Hoofdafbeelding"
        name: "image"
        widget: "image"
      - label: "Ticket Link"
        name: "ticket_link"
        widget: "string"
        required: false
      - label: "Ticket Knop Tekst"
        name: "ticket_label"
        widget: "string"
        default: "Tickets kopen"
        required: false
      - label: "Volledige Beschrijving"
        name: "body"
        widget: "markdown"

  - name: "nieuws"
    label: "Nieuws"
    folder: "src/content/nieuws"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Datum"
        name: "date"
        widget: "datetime"
      - label: "Inhoud"
        name: "body"
        widget: "markdown"
      - label: "Afbeelding"
        name: "image"
        widget: "image"
        required: false

  - name: "settings"
    label: "Instellingen"
    files:
      - label: "Ticket Prijzen"
        name: "ticket_prices"
        file: "src/data/ticket_prices.json"
        fields:
          - label: "Prijs Abonnement (in Euro)"
            name: "abonnement_price"
            widget: "number"
            value_type: "int"
            default: 26
          - label: "Link Abonnement"
            name: "abonnement_link"
            widget: "string"
            default: "https://be.ticketgang.eu/eventPackSale.php?org=204637&pack=1414"
          - label: "Prijs Voorstelling (in Euro)"
            name: "ticket_price"
            widget: "number"
            value_type: "int"
            default: 15
          - label: "Link Voorstelling"
            name: "ticket_link"
            widget: "string"
            default: "https://be.ticketgang.eu/orgFrameSaleNew.php?org=204637#"
