backend:
  name: github
  repo: darsissau/toneel-de-valk
  branch: main

site_url: https://darsissau.github.io/toneel-de-valk
display_url: https://darsissau.github.io/toneel-de-valk

media_folder: "public/images"
public_folder: "/toneel-de-valk/images"

collections:
  - name: "voorstellingen"
    label: "Voorstellingen"
    folder: "content/voorstellingen"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Datum",
          name: "date",
          widget: "datetime",
          date_format: "DD-MM-YYYY",
          time_format: false,
        }
      - { label: "Beschrijving", name: "body", widget: "markdown" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - {
          label: "Ticket link",
          name: "ticket_link",
          widget: "string",
          required: false,
        }

  - name: "nieuws"
    label: "Nieuws"
    folder: "content/nieuws"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Datum",
          name: "date",
          widget: "datetime",
          date_format: "DD-MM-YYYY",
          time_format: false,
        }
      - { label: "Inhoud", name: "body", widget: "markdown" }
      - { label: "Afbeelding", name: "image", widget: "image", required: false }
